// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/router.proto

package proto;

public final class RouterProtos {
  private RouterProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ClientRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>int64 tg_user_id = 2;</code>
     * @return The tgUserId.
     */
    long getTgUserId();

    /**
     * <code>string phone = 3;</code>
     * @return The phone.
     */
    java.lang.String getPhone();
    /**
     * <code>string phone = 3;</code>
     * @return The bytes for phone.
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>string name = 4;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string user_last_visited = 5;</code>
     * @return The userLastVisited.
     */
    java.lang.String getUserLastVisited();
    /**
     * <code>string user_last_visited = 5;</code>
     * @return The bytes for userLastVisited.
     */
    com.google.protobuf.ByteString
        getUserLastVisitedBytes();

    /**
     * <code>string vpn_profile = 6;</code>
     * @return The vpnProfile.
     */
    java.lang.String getVpnProfile();
    /**
     * <code>string vpn_profile = 6;</code>
     * @return The bytes for vpnProfile.
     */
    com.google.protobuf.ByteString
        getVpnProfileBytes();

    /**
     * <code>bool is_vpn_profile_alive = 7;</code>
     * @return The isVpnProfileAlive.
     */
    boolean getIsVpnProfileAlive();

    /**
     * <code>string expired_at = 8;</code>
     * @return The expiredAt.
     */
    java.lang.String getExpiredAt();
    /**
     * <code>string expired_at = 8;</code>
     * @return The bytes for expiredAt.
     */
    com.google.protobuf.ByteString
        getExpiredAtBytes();

    /**
     * <code>bool is_in_payment_process = 9;</code>
     * @return The isInPaymentProcess.
     */
    boolean getIsInPaymentProcess();

    /**
     * <code>string payment_key = 10;</code>
     * @return The paymentKey.
     */
    java.lang.String getPaymentKey();
    /**
     * <code>string payment_key = 10;</code>
     * @return The bytes for paymentKey.
     */
    com.google.protobuf.ByteString
        getPaymentKeyBytes();

    /**
     * <code>string balance = 11;</code>
     * @return The balance.
     */
    java.lang.String getBalance();
    /**
     * <code>string balance = 11;</code>
     * @return The bytes for balance.
     */
    com.google.protobuf.ByteString
        getBalanceBytes();

    /**
     * <code>string held_balance = 12;</code>
     * @return The heldBalance.
     */
    java.lang.String getHeldBalance();
    /**
     * <code>string held_balance = 12;</code>
     * @return The bytes for heldBalance.
     */
    com.google.protobuf.ByteString
        getHeldBalanceBytes();
  }
  /**
   * Protobuf type {@code proto.ClientRequest}
   */
  public static final class ClientRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ClientRequest)
      ClientRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientRequest.newBuilder() to construct.
    private ClientRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientRequest() {
      phone_ = "";
      name_ = "";
      userLastVisited_ = "";
      vpnProfile_ = "";
      expiredAt_ = "";
      paymentKey_ = "";
      balance_ = "";
      heldBalance_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ClientRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.RouterProtos.internal_static_proto_ClientRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.RouterProtos.internal_static_proto_ClientRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.RouterProtos.ClientRequest.class, proto.RouterProtos.ClientRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int TG_USER_ID_FIELD_NUMBER = 2;
    private long tgUserId_ = 0L;
    /**
     * <code>int64 tg_user_id = 2;</code>
     * @return The tgUserId.
     */
    @java.lang.Override
    public long getTgUserId() {
      return tgUserId_;
    }

    public static final int PHONE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object phone_ = "";
    /**
     * <code>string phone = 3;</code>
     * @return The phone.
     */
    @java.lang.Override
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <code>string phone = 3;</code>
     * @return The bytes for phone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 4;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_LAST_VISITED_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object userLastVisited_ = "";
    /**
     * <code>string user_last_visited = 5;</code>
     * @return The userLastVisited.
     */
    @java.lang.Override
    public java.lang.String getUserLastVisited() {
      java.lang.Object ref = userLastVisited_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userLastVisited_ = s;
        return s;
      }
    }
    /**
     * <code>string user_last_visited = 5;</code>
     * @return The bytes for userLastVisited.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserLastVisitedBytes() {
      java.lang.Object ref = userLastVisited_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userLastVisited_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VPN_PROFILE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object vpnProfile_ = "";
    /**
     * <code>string vpn_profile = 6;</code>
     * @return The vpnProfile.
     */
    @java.lang.Override
    public java.lang.String getVpnProfile() {
      java.lang.Object ref = vpnProfile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vpnProfile_ = s;
        return s;
      }
    }
    /**
     * <code>string vpn_profile = 6;</code>
     * @return The bytes for vpnProfile.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVpnProfileBytes() {
      java.lang.Object ref = vpnProfile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vpnProfile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_VPN_PROFILE_ALIVE_FIELD_NUMBER = 7;
    private boolean isVpnProfileAlive_ = false;
    /**
     * <code>bool is_vpn_profile_alive = 7;</code>
     * @return The isVpnProfileAlive.
     */
    @java.lang.Override
    public boolean getIsVpnProfileAlive() {
      return isVpnProfileAlive_;
    }

    public static final int EXPIRED_AT_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object expiredAt_ = "";
    /**
     * <code>string expired_at = 8;</code>
     * @return The expiredAt.
     */
    @java.lang.Override
    public java.lang.String getExpiredAt() {
      java.lang.Object ref = expiredAt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        expiredAt_ = s;
        return s;
      }
    }
    /**
     * <code>string expired_at = 8;</code>
     * @return The bytes for expiredAt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExpiredAtBytes() {
      java.lang.Object ref = expiredAt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        expiredAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_IN_PAYMENT_PROCESS_FIELD_NUMBER = 9;
    private boolean isInPaymentProcess_ = false;
    /**
     * <code>bool is_in_payment_process = 9;</code>
     * @return The isInPaymentProcess.
     */
    @java.lang.Override
    public boolean getIsInPaymentProcess() {
      return isInPaymentProcess_;
    }

    public static final int PAYMENT_KEY_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object paymentKey_ = "";
    /**
     * <code>string payment_key = 10;</code>
     * @return The paymentKey.
     */
    @java.lang.Override
    public java.lang.String getPaymentKey() {
      java.lang.Object ref = paymentKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        paymentKey_ = s;
        return s;
      }
    }
    /**
     * <code>string payment_key = 10;</code>
     * @return The bytes for paymentKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPaymentKeyBytes() {
      java.lang.Object ref = paymentKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paymentKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BALANCE_FIELD_NUMBER = 11;
    @SuppressWarnings("serial")
    private volatile java.lang.Object balance_ = "";
    /**
     * <code>string balance = 11;</code>
     * @return The balance.
     */
    @java.lang.Override
    public java.lang.String getBalance() {
      java.lang.Object ref = balance_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        balance_ = s;
        return s;
      }
    }
    /**
     * <code>string balance = 11;</code>
     * @return The bytes for balance.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBalanceBytes() {
      java.lang.Object ref = balance_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        balance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HELD_BALANCE_FIELD_NUMBER = 12;
    @SuppressWarnings("serial")
    private volatile java.lang.Object heldBalance_ = "";
    /**
     * <code>string held_balance = 12;</code>
     * @return The heldBalance.
     */
    @java.lang.Override
    public java.lang.String getHeldBalance() {
      java.lang.Object ref = heldBalance_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        heldBalance_ = s;
        return s;
      }
    }
    /**
     * <code>string held_balance = 12;</code>
     * @return The bytes for heldBalance.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHeldBalanceBytes() {
      java.lang.Object ref = heldBalance_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        heldBalance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (tgUserId_ != 0L) {
        output.writeInt64(2, tgUserId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(phone_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, phone_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userLastVisited_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userLastVisited_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vpnProfile_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, vpnProfile_);
      }
      if (isVpnProfileAlive_ != false) {
        output.writeBool(7, isVpnProfileAlive_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(expiredAt_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, expiredAt_);
      }
      if (isInPaymentProcess_ != false) {
        output.writeBool(9, isInPaymentProcess_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(paymentKey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, paymentKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(balance_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, balance_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(heldBalance_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, heldBalance_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (tgUserId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, tgUserId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(phone_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, phone_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userLastVisited_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userLastVisited_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vpnProfile_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, vpnProfile_);
      }
      if (isVpnProfileAlive_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isVpnProfileAlive_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(expiredAt_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, expiredAt_);
      }
      if (isInPaymentProcess_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, isInPaymentProcess_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(paymentKey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, paymentKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(balance_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, balance_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(heldBalance_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, heldBalance_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.RouterProtos.ClientRequest)) {
        return super.equals(obj);
      }
      proto.RouterProtos.ClientRequest other = (proto.RouterProtos.ClientRequest) obj;

      if (getId()
          != other.getId()) return false;
      if (getTgUserId()
          != other.getTgUserId()) return false;
      if (!getPhone()
          .equals(other.getPhone())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUserLastVisited()
          .equals(other.getUserLastVisited())) return false;
      if (!getVpnProfile()
          .equals(other.getVpnProfile())) return false;
      if (getIsVpnProfileAlive()
          != other.getIsVpnProfileAlive()) return false;
      if (!getExpiredAt()
          .equals(other.getExpiredAt())) return false;
      if (getIsInPaymentProcess()
          != other.getIsInPaymentProcess()) return false;
      if (!getPaymentKey()
          .equals(other.getPaymentKey())) return false;
      if (!getBalance()
          .equals(other.getBalance())) return false;
      if (!getHeldBalance()
          .equals(other.getHeldBalance())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + TG_USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTgUserId());
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + USER_LAST_VISITED_FIELD_NUMBER;
      hash = (53 * hash) + getUserLastVisited().hashCode();
      hash = (37 * hash) + VPN_PROFILE_FIELD_NUMBER;
      hash = (53 * hash) + getVpnProfile().hashCode();
      hash = (37 * hash) + IS_VPN_PROFILE_ALIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsVpnProfileAlive());
      hash = (37 * hash) + EXPIRED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getExpiredAt().hashCode();
      hash = (37 * hash) + IS_IN_PAYMENT_PROCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsInPaymentProcess());
      hash = (37 * hash) + PAYMENT_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPaymentKey().hashCode();
      hash = (37 * hash) + BALANCE_FIELD_NUMBER;
      hash = (53 * hash) + getBalance().hashCode();
      hash = (37 * hash) + HELD_BALANCE_FIELD_NUMBER;
      hash = (53 * hash) + getHeldBalance().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.RouterProtos.ClientRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RouterProtos.ClientRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RouterProtos.ClientRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RouterProtos.ClientRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RouterProtos.ClientRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RouterProtos.ClientRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RouterProtos.ClientRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RouterProtos.ClientRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RouterProtos.ClientRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.RouterProtos.ClientRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RouterProtos.ClientRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RouterProtos.ClientRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.RouterProtos.ClientRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ClientRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ClientRequest)
        proto.RouterProtos.ClientRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.RouterProtos.internal_static_proto_ClientRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.RouterProtos.internal_static_proto_ClientRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.RouterProtos.ClientRequest.class, proto.RouterProtos.ClientRequest.Builder.class);
      }

      // Construct using proto.RouterProtos.ClientRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        tgUserId_ = 0L;
        phone_ = "";
        name_ = "";
        userLastVisited_ = "";
        vpnProfile_ = "";
        isVpnProfileAlive_ = false;
        expiredAt_ = "";
        isInPaymentProcess_ = false;
        paymentKey_ = "";
        balance_ = "";
        heldBalance_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.RouterProtos.internal_static_proto_ClientRequest_descriptor;
      }

      @java.lang.Override
      public proto.RouterProtos.ClientRequest getDefaultInstanceForType() {
        return proto.RouterProtos.ClientRequest.getDefaultInstance();
      }

      @java.lang.Override
      public proto.RouterProtos.ClientRequest build() {
        proto.RouterProtos.ClientRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.RouterProtos.ClientRequest buildPartial() {
        proto.RouterProtos.ClientRequest result = new proto.RouterProtos.ClientRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(proto.RouterProtos.ClientRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.tgUserId_ = tgUserId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.phone_ = phone_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.userLastVisited_ = userLastVisited_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.vpnProfile_ = vpnProfile_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.isVpnProfileAlive_ = isVpnProfileAlive_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.expiredAt_ = expiredAt_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.isInPaymentProcess_ = isInPaymentProcess_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.paymentKey_ = paymentKey_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.balance_ = balance_;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.heldBalance_ = heldBalance_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.RouterProtos.ClientRequest) {
          return mergeFrom((proto.RouterProtos.ClientRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.RouterProtos.ClientRequest other) {
        if (other == proto.RouterProtos.ClientRequest.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getTgUserId() != 0L) {
          setTgUserId(other.getTgUserId());
        }
        if (!other.getPhone().isEmpty()) {
          phone_ = other.phone_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getUserLastVisited().isEmpty()) {
          userLastVisited_ = other.userLastVisited_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getVpnProfile().isEmpty()) {
          vpnProfile_ = other.vpnProfile_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.getIsVpnProfileAlive() != false) {
          setIsVpnProfileAlive(other.getIsVpnProfileAlive());
        }
        if (!other.getExpiredAt().isEmpty()) {
          expiredAt_ = other.expiredAt_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (other.getIsInPaymentProcess() != false) {
          setIsInPaymentProcess(other.getIsInPaymentProcess());
        }
        if (!other.getPaymentKey().isEmpty()) {
          paymentKey_ = other.paymentKey_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        if (!other.getBalance().isEmpty()) {
          balance_ = other.balance_;
          bitField0_ |= 0x00000400;
          onChanged();
        }
        if (!other.getHeldBalance().isEmpty()) {
          heldBalance_ = other.heldBalance_;
          bitField0_ |= 0x00000800;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                tgUserId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                phone_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                userLastVisited_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                vpnProfile_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 56: {
                isVpnProfileAlive_ = input.readBool();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 66: {
                expiredAt_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 72: {
                isInPaymentProcess_ = input.readBool();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 82: {
                paymentKey_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              case 90: {
                balance_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000400;
                break;
              } // case 90
              case 98: {
                heldBalance_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000800;
                break;
              } // case 98
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private long tgUserId_ ;
      /**
       * <code>int64 tg_user_id = 2;</code>
       * @return The tgUserId.
       */
      @java.lang.Override
      public long getTgUserId() {
        return tgUserId_;
      }
      /**
       * <code>int64 tg_user_id = 2;</code>
       * @param value The tgUserId to set.
       * @return This builder for chaining.
       */
      public Builder setTgUserId(long value) {
        
        tgUserId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 tg_user_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTgUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tgUserId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object phone_ = "";
      /**
       * <code>string phone = 3;</code>
       * @return The phone.
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phone = 3;</code>
       * @return The bytes for phone.
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phone = 3;</code>
       * @param value The phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        phone_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhone() {
        phone_ = getDefaultInstance().getPhone();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 3;</code>
       * @param value The bytes for phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        phone_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 4;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object userLastVisited_ = "";
      /**
       * <code>string user_last_visited = 5;</code>
       * @return The userLastVisited.
       */
      public java.lang.String getUserLastVisited() {
        java.lang.Object ref = userLastVisited_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userLastVisited_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_last_visited = 5;</code>
       * @return The bytes for userLastVisited.
       */
      public com.google.protobuf.ByteString
          getUserLastVisitedBytes() {
        java.lang.Object ref = userLastVisited_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userLastVisited_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_last_visited = 5;</code>
       * @param value The userLastVisited to set.
       * @return This builder for chaining.
       */
      public Builder setUserLastVisited(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userLastVisited_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string user_last_visited = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserLastVisited() {
        userLastVisited_ = getDefaultInstance().getUserLastVisited();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string user_last_visited = 5;</code>
       * @param value The bytes for userLastVisited to set.
       * @return This builder for chaining.
       */
      public Builder setUserLastVisitedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userLastVisited_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object vpnProfile_ = "";
      /**
       * <code>string vpn_profile = 6;</code>
       * @return The vpnProfile.
       */
      public java.lang.String getVpnProfile() {
        java.lang.Object ref = vpnProfile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          vpnProfile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string vpn_profile = 6;</code>
       * @return The bytes for vpnProfile.
       */
      public com.google.protobuf.ByteString
          getVpnProfileBytes() {
        java.lang.Object ref = vpnProfile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vpnProfile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string vpn_profile = 6;</code>
       * @param value The vpnProfile to set.
       * @return This builder for chaining.
       */
      public Builder setVpnProfile(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        vpnProfile_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string vpn_profile = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearVpnProfile() {
        vpnProfile_ = getDefaultInstance().getVpnProfile();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string vpn_profile = 6;</code>
       * @param value The bytes for vpnProfile to set.
       * @return This builder for chaining.
       */
      public Builder setVpnProfileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        vpnProfile_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private boolean isVpnProfileAlive_ ;
      /**
       * <code>bool is_vpn_profile_alive = 7;</code>
       * @return The isVpnProfileAlive.
       */
      @java.lang.Override
      public boolean getIsVpnProfileAlive() {
        return isVpnProfileAlive_;
      }
      /**
       * <code>bool is_vpn_profile_alive = 7;</code>
       * @param value The isVpnProfileAlive to set.
       * @return This builder for chaining.
       */
      public Builder setIsVpnProfileAlive(boolean value) {
        
        isVpnProfileAlive_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_vpn_profile_alive = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsVpnProfileAlive() {
        bitField0_ = (bitField0_ & ~0x00000040);
        isVpnProfileAlive_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object expiredAt_ = "";
      /**
       * <code>string expired_at = 8;</code>
       * @return The expiredAt.
       */
      public java.lang.String getExpiredAt() {
        java.lang.Object ref = expiredAt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          expiredAt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string expired_at = 8;</code>
       * @return The bytes for expiredAt.
       */
      public com.google.protobuf.ByteString
          getExpiredAtBytes() {
        java.lang.Object ref = expiredAt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          expiredAt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string expired_at = 8;</code>
       * @param value The expiredAt to set.
       * @return This builder for chaining.
       */
      public Builder setExpiredAt(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        expiredAt_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string expired_at = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearExpiredAt() {
        expiredAt_ = getDefaultInstance().getExpiredAt();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string expired_at = 8;</code>
       * @param value The bytes for expiredAt to set.
       * @return This builder for chaining.
       */
      public Builder setExpiredAtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        expiredAt_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private boolean isInPaymentProcess_ ;
      /**
       * <code>bool is_in_payment_process = 9;</code>
       * @return The isInPaymentProcess.
       */
      @java.lang.Override
      public boolean getIsInPaymentProcess() {
        return isInPaymentProcess_;
      }
      /**
       * <code>bool is_in_payment_process = 9;</code>
       * @param value The isInPaymentProcess to set.
       * @return This builder for chaining.
       */
      public Builder setIsInPaymentProcess(boolean value) {
        
        isInPaymentProcess_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_in_payment_process = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsInPaymentProcess() {
        bitField0_ = (bitField0_ & ~0x00000100);
        isInPaymentProcess_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object paymentKey_ = "";
      /**
       * <code>string payment_key = 10;</code>
       * @return The paymentKey.
       */
      public java.lang.String getPaymentKey() {
        java.lang.Object ref = paymentKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          paymentKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string payment_key = 10;</code>
       * @return The bytes for paymentKey.
       */
      public com.google.protobuf.ByteString
          getPaymentKeyBytes() {
        java.lang.Object ref = paymentKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          paymentKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string payment_key = 10;</code>
       * @param value The paymentKey to set.
       * @return This builder for chaining.
       */
      public Builder setPaymentKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        paymentKey_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>string payment_key = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearPaymentKey() {
        paymentKey_ = getDefaultInstance().getPaymentKey();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>string payment_key = 10;</code>
       * @param value The bytes for paymentKey to set.
       * @return This builder for chaining.
       */
      public Builder setPaymentKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        paymentKey_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      private java.lang.Object balance_ = "";
      /**
       * <code>string balance = 11;</code>
       * @return The balance.
       */
      public java.lang.String getBalance() {
        java.lang.Object ref = balance_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          balance_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string balance = 11;</code>
       * @return The bytes for balance.
       */
      public com.google.protobuf.ByteString
          getBalanceBytes() {
        java.lang.Object ref = balance_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          balance_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string balance = 11;</code>
       * @param value The balance to set.
       * @return This builder for chaining.
       */
      public Builder setBalance(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        balance_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>string balance = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearBalance() {
        balance_ = getDefaultInstance().getBalance();
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
        return this;
      }
      /**
       * <code>string balance = 11;</code>
       * @param value The bytes for balance to set.
       * @return This builder for chaining.
       */
      public Builder setBalanceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        balance_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }

      private java.lang.Object heldBalance_ = "";
      /**
       * <code>string held_balance = 12;</code>
       * @return The heldBalance.
       */
      public java.lang.String getHeldBalance() {
        java.lang.Object ref = heldBalance_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          heldBalance_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string held_balance = 12;</code>
       * @return The bytes for heldBalance.
       */
      public com.google.protobuf.ByteString
          getHeldBalanceBytes() {
        java.lang.Object ref = heldBalance_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          heldBalance_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string held_balance = 12;</code>
       * @param value The heldBalance to set.
       * @return This builder for chaining.
       */
      public Builder setHeldBalance(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        heldBalance_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>string held_balance = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeldBalance() {
        heldBalance_ = getDefaultInstance().getHeldBalance();
        bitField0_ = (bitField0_ & ~0x00000800);
        onChanged();
        return this;
      }
      /**
       * <code>string held_balance = 12;</code>
       * @param value The bytes for heldBalance to set.
       * @return This builder for chaining.
       */
      public Builder setHeldBalanceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        heldBalance_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ClientRequest)
    }

    // @@protoc_insertion_point(class_scope:proto.ClientRequest)
    private static final proto.RouterProtos.ClientRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.RouterProtos.ClientRequest();
    }

    public static proto.RouterProtos.ClientRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientRequest>
        PARSER = new com.google.protobuf.AbstractParser<ClientRequest>() {
      @java.lang.Override
      public ClientRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ClientRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.RouterProtos.ClientRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code proto.ResponseMessage}
   */
  public static final class ResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ResponseMessage)
      ResponseMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseMessage.newBuilder() to construct.
    private ResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseMessage() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResponseMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.RouterProtos.internal_static_proto_ResponseMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.RouterProtos.internal_static_proto_ResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.RouterProtos.ResponseMessage.class, proto.RouterProtos.ResponseMessage.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.RouterProtos.ResponseMessage)) {
        return super.equals(obj);
      }
      proto.RouterProtos.ResponseMessage other = (proto.RouterProtos.ResponseMessage) obj;

      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.RouterProtos.ResponseMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RouterProtos.ResponseMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RouterProtos.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RouterProtos.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RouterProtos.ResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RouterProtos.ResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RouterProtos.ResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RouterProtos.ResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RouterProtos.ResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.RouterProtos.ResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RouterProtos.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RouterProtos.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.RouterProtos.ResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ResponseMessage)
        proto.RouterProtos.ResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.RouterProtos.internal_static_proto_ResponseMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.RouterProtos.internal_static_proto_ResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.RouterProtos.ResponseMessage.class, proto.RouterProtos.ResponseMessage.Builder.class);
      }

      // Construct using proto.RouterProtos.ResponseMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        message_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.RouterProtos.internal_static_proto_ResponseMessage_descriptor;
      }

      @java.lang.Override
      public proto.RouterProtos.ResponseMessage getDefaultInstanceForType() {
        return proto.RouterProtos.ResponseMessage.getDefaultInstance();
      }

      @java.lang.Override
      public proto.RouterProtos.ResponseMessage build() {
        proto.RouterProtos.ResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.RouterProtos.ResponseMessage buildPartial() {
        proto.RouterProtos.ResponseMessage result = new proto.RouterProtos.ResponseMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(proto.RouterProtos.ResponseMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.message_ = message_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.RouterProtos.ResponseMessage) {
          return mergeFrom((proto.RouterProtos.ResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.RouterProtos.ResponseMessage other) {
        if (other == proto.RouterProtos.ResponseMessage.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 1;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:proto.ResponseMessage)
    private static final proto.RouterProtos.ResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.RouterProtos.ResponseMessage();
    }

    public static proto.RouterProtos.ResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResponseMessage>() {
      @java.lang.Override
      public ResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResponseMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.RouterProtos.ResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ClientRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ClientRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022proto/router.proto\022\005proto\"\211\002\n\rClientRe" +
      "quest\022\n\n\002id\030\001 \001(\003\022\022\n\ntg_user_id\030\002 \001(\003\022\r\n" +
      "\005phone\030\003 \001(\t\022\014\n\004name\030\004 \001(\t\022\031\n\021user_last_" +
      "visited\030\005 \001(\t\022\023\n\013vpn_profile\030\006 \001(\t\022\034\n\024is" +
      "_vpn_profile_alive\030\007 \001(\010\022\022\n\nexpired_at\030\010" +
      " \001(\t\022\035\n\025is_in_payment_process\030\t \001(\010\022\023\n\013p" +
      "ayment_key\030\n \001(\t\022\017\n\007balance\030\013 \001(\t\022\024\n\014hel" +
      "d_balance\030\014 \001(\t\"\"\n\017ResponseMessage\022\017\n\007me" +
      "ssage\030\001 \001(\t2\333\001\n\017RouterConnector\022D\n\024Initi" +
      "alisationSecret\022\024.proto.ClientRequest\032\026." +
      "proto.ResponseMessage\022C\n\023InitialisationT" +
      "rial\022\024.proto.ClientRequest\032\026.proto.Respo" +
      "nseMessage\022=\n\rProlongSecret\022\024.proto.Clie" +
      "ntRequest\032\026.proto.ResponseMessageB\025\n\005pro" +
      "toB\014RouterProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_ClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ClientRequest_descriptor,
        new java.lang.String[] { "Id", "TgUserId", "Phone", "Name", "UserLastVisited", "VpnProfile", "IsVpnProfileAlive", "ExpiredAt", "IsInPaymentProcess", "PaymentKey", "Balance", "HeldBalance", });
    internal_static_proto_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ResponseMessage_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
