services:
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: MickroTikBot
    networks:
      - botnet
    depends_on:
      - chr
      - postgresql
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always

  chr:
    build: ./docker/chr
    container_name: chr_router
    privileged: true
    networks:
      - botnet
    ports:
      - "2222:2222"
    depends_on:
      - postgresql
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always

  postgresql:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: table
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    networks:
      - botnet

    restart: always
  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/table
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
        - botnet

networks:
  botnet:
    driver: bridge
volumes:
  postgresql: { }