services:
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: MickroTikBot
    networks:
      - botnet
    depends_on:
      - chr
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always

  chr:
    build: ./docker/chr
    container_name: chr_router
    privileged: true
    networks:
      - botnet
    ports:
      - "2222:2222"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always

networks:
  botnet:
    driver: bridge
volumes:
  postgresql: { }